spring.application.name=vitae-api

# Database Configuration (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/vitae_db}
spring.datasource.username=${DB_USER:vitae_db_admin}
spring.datasource.password=${DB_PASSWORD:Vitae_Secure#2026}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Evita erro de serialização com proxies Hibernate (ByteBuddyInterceptor)
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
